### ISSUE TITLE
[bugs] Run error in ArchLinux

### ISSUE THREAD

**Issue by zxp19821005** [mihnea-radulescu/imagefanreloaded#1]
```
$ ./src/ImageFanReloaded-Avalonia-Linux-x64/ImageFanReloaded-Avalonia       
You must install or update .NET to run this application.

App: /home/zxp-endeavouros/.cache/paru/clone/imagefanreloaded-avalonia-bin/src/ImageFanReloaded-Avalonia-Linux-x64/ImageFanReloaded-Avalonia
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  7.0.10 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=endeavouros-x64
```
Then I installed the `dotnet-runtime-6.0` by
```
sudo pacman -Sy dotnet-runtime-6.0
```
and I run the program again,I got these errors:
```
$ ./src/ImageFanReloaded-Avalonia-Linux-x64/ImageFanReloaded-Avalonia
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.AppBuilder.<>c__DisplayClass62_0.<ConfigureFonts>b__0(AppBuilder appBuilder)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at ImageFanReloaded.Program.Main(String[] args) in C:\Repositories\imagefanreloaded\ImageFanReloaded-Avalonia\Program.cs:line 10
[1]    244527 IOT instruction (core dumped)  ./src/ImageFanReloaded-Avalonia-Linux-x64/ImageFanReloaded-Avalonia
```

**Comment by mihnea-radulescu** [comment]
Thank you very much for raising this issue!

The error stems from an [unresolved bug](https://github.com/AvaloniaUI/Avalonia/issues/4427) in the Avalonia framework that is used by the image viewer.

There appears to be a [workaround](https://github.com/icsharpcode/AvaloniaILSpy/issues/84) specifically for Arch Linux, which requires the font **ttf-dejavu** to be installed.

Please let me know if this workaround solves the matter for you.

**Comment by zxp19821005** [comment]
Still got errors.
The `PKGBUILD` file you can see: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=imagefanreloaded-avalonia-bin
When I add the `ttf-dejavu`,and make it,I got this:
```
$ imagefanreloaded-avalonia
Failure processing application bundle; possible file corruption.
Arithmetic overflow while reading bundle.
A fatal error occurred while processing application bundle
```

**Comment by zxp19821005** [comment]
Still got errors:
```
$ chmod +x src/ImageFanReloaded-Avalonia-Linux-x64/ImageFanReloaded-Avalonia 

# zxp-endeavouros @ 3993EndeavourOS in ~/.cache/paru/clone/imagefanreloaded-avalonia-bin on git:master x [9:53:19] 
$ ./src/ImageFanReloaded-Avalonia-Linux-x64/ImageFanReloaded-Avalonia 
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.AppBuilder.<>c__DisplayClass62_0.<ConfigureFonts>b__0(AppBuilder appBuilder)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at ImageFanReloaded.Program.Main(String[] args) in C:\Repositories\imagefanreloaded\ImageFanReloaded-Avalonia\Program.cs:line 10
[1]    1781868 IOT instruction (core dumped)  ./src/ImageFanReloaded-Avalonia-Linux-x64/ImageFanReloaded-Avalonia
```
After build:
```
$ ./pkg/imagefanreloaded-avalonia-bin/opt/imagefanreloaded-avalonia/ImageFanReloaded-Avalonia 
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.AppBuilder.<>c__DisplayClass62_0.<ConfigureFonts>b__0(AppBuilder appBuilder)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at ImageFanReloaded.Program.Main(String[] args) in C:\Repositories\imagefanreloaded\ImageFanReloaded-Avalonia\Program.cs:line 10
[1]    1780301 IOT instruction (core dumped)
```

**Comment by zxp19821005** [comment]
Is there any configure file?

**Comment by mihnea-radulescu** [comment]
I've considered bypassing the Avalonia "System.InvalidOperationException: Default font family name can't be null or empty." bug by setting a default font family for Linux.

This idea, however, does not help matters, as no font can be relied to always be present on every Linux system, and Avalonia does not allow for a generic font family to be specified, such as "sans-serif".

The only option remaining, unless the Avalonia bug gets fixed, is to include the package [ttf-ms-fonts](https://aur.archlinux.org/packages/ttf-ms-fonts) in the PKGBUILD.

Hopefully this will fix this issue.

**Comment by zxp19821005** [comment]
I've add the dependicy `ttf-ms-fonts`,but still got the same error.

**Comment by zxp19821005** [comment]
I met the same problem in ULogViewer(https://github.com/carina-studio/ULogViewer/issues/21),but the author has solved it,maybe you can ask him for help.

**Comment by mihnea-radulescu** [comment]
Hi @zxp19821005,

I have released today a new version of the software, which includes a [partial fix](https://github.com/AvaloniaUI/Avalonia/pull/12817) to the [issue](https://github.com/AvaloniaUI/Avalonia/issues/4427) you encountered.

Could you please re-test with the new version?

**Comment by zxp19821005** [comment]
Still error:
```
$ imagefanreloaded-avalonia
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.AppBuilder.<>c__DisplayClass62_0.<ConfigureFonts>b__0(AppBuilder appBuilder)
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at ImageFanReloaded.Program.Main(String[] args) in C:\Repositories\imagefanreloaded\ImageFanReloaded-Avalonia\Program.cs:line 10
[1]    213128 IOT instruction (core dumped)  imagefanreloaded-avalonia
```

**Comment by memorydream** [comment]
Hi, I saw this issue link from AvaloniaILSpy, you can try `export LC_CTYPE=en_US.UTF-8` before run Avalonia application, or set in `/etc/locale.conf`, it should can resolve font issue

If you are running KDE Plasma, sholud check system settings, not locale.conf, please see https://wiki.archlinux.org/title/locale#My_system_is_still_using_wrong_language

**Comment by zxp19821005** [comment]
@memorydream Thanks a lot,fixed it now.
@mihnea-radulescu Thank you,it run well now.

**Comment by mihnea-radulescu** [comment]
Thank you very much @memorydream and @zxp19821005 for providing and confirming the fix to this issue.
